Merge Features to Dev branch-Code Review
MephistoDevelop/tic-tac-toe pull request #2
Opened 2020-01-10 19:20 UTC by MephistoDevelop

Request to Code review with the next features:
-Create User Interface
-Start a new game
-Play a turn for each player
-Create Board with dynamical elements

2020-01-13 06:22 UTC, mcrd25 requested changes
# Changes Required 👀 🔍 

Hi, @MephistoDevelop and @ansaryergesh 👋 ,

Your Tic Tac Toe interface looks good! And your README is excellent 👏!
However, there are still quite a few things to work on to make this project excellent and for it to be an even better addition to your portfolio.

### REquired Changes
- The goal of the project was to use as little global code as possible. As mentioned in the [Odin](https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript) description. You were actually supposed to encapsulate your logic into factories or modules as seen from this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png). Please do this! 🙏 
- You need a game, gameBoard and player modules/factory. Hint 💡 player is best suited to be a factory.
- You ought to have a gameboard array (this could be in your gameBoard modules) and a function whose sole purpose is to render its contents as seen from this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/objects_requirement.png)
- Your winning method does not seem to compute the winner accurately as when I play I do not get correct feedback that I've won as seen from these screenshots. This is a requirement
![Screen Shot 2020-01-13 at 2 12 20 AM](https://user-images.githubusercontent.com/31193823/72235848-b411cf80-35aa-11ea-8f45-e3e2d115b822.png)
![Screen Shot 2020-01-13 at 2 12 27 AM](https://user-images.githubusercontent.com/31193823/72235849-b411cf80-35aa-11ea-946b-59dacebc1a67.png)

### Suggested [OPTIONAL]
- Consider using ES6 syntax [OPTIONAL]

*Ultimately you ought to have at least 3 files. Your main app file and 3 files for your `game` module, `gameBoard` module and `player` factory. And you will import your modules/factory into your app.js (main file) and call methods there from those objects. Try to have as little code in your `app.js` as possible.*

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-01-13 06:22 UTC, mcrd25 commented on index.html
> +      <button id="button" onclick="refresh();">New Game</button>
You really ought to handle these onclicks in javascript script with an event handler.
Please do 🙏

2020-01-13 06:22 UTC, mcrd25 commented on index.html
> +      <input type="button" onclick="giveName();" id="btn-play" value="play" />
You really ought to handle this onclick in javascript script with an event handler.
Please do 🙏

2020-01-13 06:22 UTC, mcrd25 commented on index.html
> +  <body onload="resetGame();">
Try and handle this from the JavaScript file

2020-01-15 22:56 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED 

Hi  Team, good job starting out on this and trying to fix the suggestions from previous review :+1: , please see more suggestions below  

I couldn't run this because the right javascript file was not linked to this project , please look into that 
**Please make changes and request for another review**

**RAPHAEL NORIODE** :sunglasses:

2020-01-15 22:56 UTC, Oghenebrume50 commented on dist/index.html
> +    <script type="module" src="js/board.js"></script>
Please where does the src attribute link to, I cannot see a js folder

2020-01-15 22:56 UTC, Oghenebrume50 commented on src/index.js
> +let messageText;
You really do not need these globals ![screen](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png)

Creating reuasable objects is better, check out factory functions

2020-01-15 22:56 UTC, Oghenebrume50 commented on src/index.js
> +    Board.drawBoard();
[OPTIONAL] The player class should handle player logic, calling the board here to draw it, just shows how it doesn't do that very well

2020-02-03 22:35 UTC, closed without merging